"""RBAC 角色元组常量（与各路由 Depends(require_roles(*...))) 配对）。

对齐概要：docs/01_需求文档/03_角色权限与数据安全架构设计.md
"""

RBAC_ASSET_READ = (
    "SYS_ADMIN",
    "DEVICE_ADMIN",
    "ENGINEER",
    "DEPT_USER",
    "AUDIT_ADMIN",
)

RBAC_ASSET_WRITE = ("SYS_ADMIN", "DEVICE_ADMIN")

RBAC_REPAIR_READ = RBAC_ASSET_READ

RBAC_REPAIR_CREATE = ("SYS_ADMIN", "DEVICE_ADMIN", "DEPT_USER", "ENGINEER")

RBAC_REPAIR_ENGINEER_OPS = ("SYS_ADMIN", "DEVICE_ADMIN", "ENGINEER")

RBAC_REPAIR_ASSIGN = ("SYS_ADMIN", "DEVICE_ADMIN")

RBAC_REPAIR_CONFIRM = ("SYS_ADMIN", "DEVICE_ADMIN", "DEPT_USER")

RBAC_REPAIR_EXTENDED_WORK = RBAC_REPAIR_ENGINEER_OPS

# PM 预防性维护：对齐 docs/06_接口设计/01 · 十
RBAC_PM_READ = RBAC_ASSET_READ
RBAC_PM_WRITE = RBAC_ASSET_WRITE
RBAC_PM_EXECUTE = RBAC_REPAIR_ENGINEER_OPS

# 计量与合规：对齐 docs/06_接口设计/01 · 十一
RBAC_METROLOGY_READ = RBAC_ASSET_READ
RBAC_METROLOGY_WRITE = RBAC_ASSET_WRITE

# 数字运营中心：院内管理端配置大屏、密钥、终端与访问审计。
RBAC_OPERATION_CENTER_READ = RBAC_ASSET_READ
RBAC_OPERATION_CENTER_WRITE = RBAC_ASSET_WRITE

# AI / 知识库：对齐 docs/06_接口设计/01_API接口设计.md §六、§七
RBAC_AI_TASK_CREATE = ("SYS_ADMIN", "DEVICE_ADMIN", "ENGINEER", "DEPT_USER")
RBAC_AI_TASK_READ = RBAC_ASSET_READ
RBAC_AI_RESULT_REVIEW = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")

RBAC_KNOWLEDGE_READ = RBAC_ASSET_READ
RBAC_KNOWLEDGE_WRITE = RBAC_ASSET_WRITE

# 工作流：对齐 docs/06_接口设计/01 §八
RBAC_WORKFLOW_START = ("SYS_ADMIN", "DEVICE_ADMIN", "DEPT_USER")
RBAC_WORKFLOW_TASK_READ = RBAC_ASSET_READ

# 外修竞价项目（院内 `/supplier-projects`）：对齐 docs/06_接口设计/01 §三
RBAC_PROCUREMENT_PUBLISH = ("SYS_ADMIN", "DEVICE_ADMIN")
RBAC_PROCUREMENT_READ = RBAC_ASSET_READ
RBAC_PROCUREMENT_REVIEW = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")

# 供应商资质院内审核：docs/06_接口设计/01 §三·7～8（路径 `/suppliers/qualifications`）
RBAC_SUPPLIER_QUALIFICATION_READ = RBAC_PROCUREMENT_READ
RBAC_SUPPLIER_QUALIFICATION_REVIEW = RBAC_PROCUREMENT_REVIEW

# 财务发票：对齐 docs/06_接口设计/01 §五
RBAC_FINANCE_READ = RBAC_ASSET_READ
RBAC_FINANCE_UPLOAD = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")
RBAC_FINANCE_REVIEW = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")
RBAC_FINANCE_PAY = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")

# 系统用户与角色：docs/06_接口设计/01_API接口设计.md §十三
RBAC_SYSTEM_USER_READ = ("SYS_ADMIN", "DEVICE_ADMIN", "AUDIT_ADMIN")
RBAC_SYSTEM_USER_WRITE = ("SYS_ADMIN",)
